import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import {Toaster} from "sonner";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import AlertCookieAccept from "@/components/features/AlertCookieAccept";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <AlertCookieAccept />
        <Header />
        <div className="max-w-6xl mx-auto w-full mt-8">
          {children}
        </div>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
